"use client";
import { use } from "react";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { useNetworking } from "@/hooks/useNetworking";

export default function NetworkingPage({ params }: { params: Promise<{ eventId: string }> }) {
  const { eventId } = use(params);
  const { config, participants, connections, reports, metrics, saveConfig, updateReport, block, participantPage, setParticipantPage, participantSearch, setParticipantSearch, participantOrganization, setParticipantOrganization, participantDesignation, setParticipantDesignation, connectionPage, setConnectionPage, connectionStatus, setConnectionStatus, connectionSearch, setConnectionSearch } = useNetworking(eventId);
  if (config.isLoading || participants.isLoading || connections.isLoading || reports.isLoading || metrics.isLoading) return <p className="p-6">Loading networking...</p>;
  if (config.isError || participants.isError || connections.isError || reports.isError || metrics.isError) return <p className="p-6 text-red-500">Unable to load networking.</p>;
  const current = config.data ?? { enabled: false, matchmaking_enabled: true, allowed_participant_types: null };
  return <div className="space-y-6">
    <Link href={`/ops/events/${eventId}`} className="flex items-center gap-2 text-sm text-[var(--foreground-muted)]"><ArrowLeft className="h-4 w-4" /> Back to event</Link>
    <header><h1 className="text-2xl font-semibold">Participant networking</h1><p className="text-sm text-[var(--foreground-muted)]">Event-scoped privacy, matchmaking, connections, and reports</p></header>
    <section className="flex flex-wrap gap-3">{metrics.data && Object.entries(metrics.data).map(([key, value]) => <div key={key} className="rounded-xl border p-3"><p className="text-xs uppercase text-[var(--foreground-muted)]">{key.replaceAll("_", " ")}</p><p className="text-2xl font-semibold">{value}</p></div>)}</section>
    <section className="rounded-xl border p-4"><h2 className="mb-3 text-lg font-semibold">Configuration</h2><div className="flex gap-4"><label><input type="checkbox" checked={current.enabled} onChange={(e) => saveConfig.mutate({ ...current, enabled: e.target.checked })} /> Enable networking</label><label><input type="checkbox" checked={current.matchmaking_enabled} onChange={(e) => saveConfig.mutate({ ...current, matchmaking_enabled: e.target.checked })} /> Enable matchmaking</label></div></section>
    <section className="rounded-xl border p-4"><h2 className="mb-3 text-lg font-semibold">Discoverable participants</h2><div className="mb-3 flex flex-wrap gap-2"><input className="rounded-md border px-3 py-2" value={participantSearch} onChange={(e) => { setParticipantSearch(e.target.value); setParticipantPage(1); }} placeholder="Search participants" /><input className="rounded-md border px-3 py-2" value={participantOrganization} onChange={(e) => { setParticipantOrganization(e.target.value); setParticipantPage(1); }} placeholder="Organization" /><input className="rounded-md border px-3 py-2" value={participantDesignation} onChange={(e) => { setParticipantDesignation(e.target.value); setParticipantPage(1); }} placeholder="Designation" /></div>{participants.data?.items.length ? <div className="space-y-2">{participants.data.items.map((person) => <div key={person.id} className="rounded-lg border p-3"><p className="font-medium">{person.display_name ?? "Unnamed participant"}</p><p className="text-sm text-[var(--foreground-muted)]">{person.organization ?? ""} {person.designation ? `· ${person.designation}` : ""}</p></div>)}</div> : <p className="text-sm text-[var(--foreground-muted)]">No opted-in participants.</p>}<Pager page={participantPage} total={participants.data?.total ?? 0} onPage={setParticipantPage} /></section>
    <section className="rounded-xl border p-4"><h2 className="mb-3 text-lg font-semibold">Connections</h2><div className="mb-3 flex gap-2"><input className="rounded-md border px-3 py-2" value={connectionSearch} onChange={(e) => { setConnectionSearch(e.target.value); setConnectionPage(1); }} placeholder="Search participant" /><select className="rounded-md border px-3 py-2" value={connectionStatus ?? ""} onChange={(e) => { setConnectionStatus(e.target.value ? e.target.value as never : undefined); setConnectionPage(1); }}><option value="">All statuses</option><option value="pending">Pending</option><option value="accepted">Accepted</option><option value="rejected">Rejected</option><option value="cancelled">Cancelled</option><option value="blocked">Blocked</option></select></div>{connections.data?.items.length ? <div className="space-y-2">{connections.data.items.map((connection) => <div key={connection.id} className="rounded-lg border p-3"><p className="font-medium">{connection.status}</p><p className="text-sm text-[var(--foreground-muted)]">Intent: {connection.intent}</p></div>)}</div> : <p className="text-sm text-[var(--foreground-muted)]">No connections found.</p>}<Pager page={connectionPage} total={connections.data?.total ?? 0} onPage={setConnectionPage} /></section>
    <section className="rounded-xl border p-4"><h2 className="mb-3 text-lg font-semibold">Reports</h2>{reports.data?.items.length ? <div className="space-y-2">{reports.data.items.map((report) => <div key={report.id} className="flex items-center justify-between rounded-lg border p-3"><div><p>{report.reason}</p><p className="text-xs text-[var(--foreground-muted)]">{report.status}</p></div><div className="flex gap-2">{report.status === "open" && <button className="rounded-md border px-3 py-1 text-sm" onClick={() => updateReport.mutate({ id: report.id, status: "reviewed" })}>Mark reviewed</button>}<button className="rounded-md border px-3 py-1 text-sm" onClick={() => block.mutate(report.reported_user_id)}>Block participant</button></div></div>)}</div> : <p className="text-sm text-[var(--foreground-muted)]">No reports.</p>}</section>
  </div>;
}

function Pager({ page, total, onPage }: { page: number; total: number; onPage: (page: number) => void }) {
  const maxPage = Math.max(1, Math.ceil(total / 25));
  return <div className="mt-4 flex items-center justify-between text-sm"><span>Page {page} of {maxPage}</span><div className="flex gap-2"><button className="rounded-md border px-3 py-1 disabled:opacity-50" disabled={page <= 1} onClick={() => onPage(page - 1)}>Previous</button><button className="rounded-md border px-3 py-1 disabled:opacity-50" disabled={page >= maxPage} onClick={() => onPage(page + 1)}>Next</button></div></div>;
}
