import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { cancelAccessTransfer, createAccessZone, listAccessPolicies, listAccessTickets, listAccessTransfers, listAccessZones, reassignAccessTicket, revokeAccessTicket, upsertAccessPolicy } from "@/api/access";
import { useSessionStore } from "@/state/sessionStore";
export function useAccess(eventId: string) { const ready = useSessionStore((s) => s.hydrated && !!s.user); return { zones: useQuery({ queryKey: ["access", eventId, "zones"], queryFn: () => listAccessZones(eventId), enabled: ready && !!eventId }), policies: useQuery({ queryKey: ["access", eventId, "policies"], queryFn: () => listAccessPolicies(eventId), enabled: ready && !!eventId }), tickets: useQuery({ queryKey: ["access", eventId, "tickets"], queryFn: () => listAccessTickets(eventId), enabled: ready && !!eventId }) }; }
export function useRevokeAccessTicket(eventId: string) { const client = useQueryClient(); return useMutation({ mutationFn: (ticketId: string) => revokeAccessTicket(eventId, ticketId), onSuccess: () => client.invalidateQueries({ queryKey: ["access", eventId] }) }); }
export function useReassignAccessTicket(eventId: string) { const client = useQueryClient(); return useMutation({ mutationFn: ({ ticketId, userId }: { ticketId: string; userId: string }) => reassignAccessTicket(eventId, ticketId, userId), onSuccess: () => client.invalidateQueries({ queryKey: ["access", eventId] }) }); }
export function useAccessTransfers(eventId: string, filters: { status?: string; search?: string; page?: number } = {}) { const ready = useSessionStore((s) => s.hydrated && !!s.user); return useQuery({ queryKey: ["access", eventId, "transfers", filters], queryFn: () => listAccessTransfers(eventId, filters), enabled: ready && !!eventId }); }
export function useCancelAccessTransfer(eventId: string) { const client = useQueryClient(); return useMutation({ mutationFn: (transferId: string) => cancelAccessTransfer(eventId, transferId), onSuccess: () => client.invalidateQueries({ queryKey: ["access", eventId, "transfers"] }) }); }
export function useCreateAccessZone(eventId: string) { const client = useQueryClient(); return useMutation({ mutationFn: (payload: { code: string; name: string }) => createAccessZone(eventId, payload), onSuccess: () => client.invalidateQueries({ queryKey: ["access", eventId, "zones"] }) }); }
export function useUpsertAccessPolicy(eventId: string) { const client = useQueryClient(); return useMutation({ mutationFn: (payload: { access_type: string; allows_reentry: boolean; max_entries: number; valid_dates?: string[] }) => upsertAccessPolicy(eventId, payload), onSuccess: () => client.invalidateQueries({ queryKey: ["access", eventId, "policies"] }) }); }
