import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { awardBadge, issueCertificate, listBadgeAwards, listBadgeDefinitions, listCertificateTemplates, listEligibleBadgeParticipants, listEligibleParticipants, listEventCertificates, revokeBadge, revokeCertificate, upsertBadgeDefinition, upsertCertificateTemplate } from "@/api/certificates";
import { useSessionStore } from "@/state/sessionStore";
export function useCertificateTemplates(eventId: string) { const ready = useSessionStore((s) => s.hydrated && !!s.user); return useQuery({ queryKey: ["certificates", eventId, "templates"], queryFn: () => listCertificateTemplates(eventId), enabled: ready && !!eventId }); }
export function useUpsertCertificateTemplate(eventId: string) { const client = useQueryClient(); return useMutation({ mutationFn: (payload: Partial<import("@/types/certificates").CertificateTemplate>) => upsertCertificateTemplate(eventId, payload), onSuccess: () => client.invalidateQueries({ queryKey: ["certificates", eventId] }) }); }
export function useUpsertBadgeDefinition(eventId: string) { const client = useQueryClient(); return useMutation({ mutationFn: (payload: Partial<import("@/types/certificates").BadgeDefinition>) => upsertBadgeDefinition(eventId, payload), onSuccess: () => client.invalidateQueries({ queryKey: ["certificates", eventId] }) }); }
export function useEventCertificates(eventId: string, status?: string) { const ready = useSessionStore((s) => s.hydrated && !!s.user); return useQuery({ queryKey: ["certificates", eventId, "issued", status], queryFn: () => listEventCertificates(eventId, { status }), enabled: ready && !!eventId }); }
export function useIssueCertificate(eventId: string) { const client = useQueryClient(); return useMutation({ mutationFn: ({ templateId, registrationId, participantId }: { templateId: string; registrationId: string; participantId?: string | null }) => issueCertificate(eventId, templateId, registrationId, participantId), onSuccess: () => client.invalidateQueries({ queryKey: ["certificates", eventId] }) }); }
export function useRevokeCertificate(eventId: string) { const client = useQueryClient(); return useMutation({ mutationFn: (certificateId: string) => revokeCertificate(certificateId), onSuccess: () => client.invalidateQueries({ queryKey: ["certificates", eventId] }) }); }
export function useEligibleParticipants(eventId: string, templateId?: string, search?: string) { const ready = useSessionStore((s) => s.hydrated && !!s.user); return useQuery({ queryKey: ["certificates", eventId, "eligible", templateId, search], queryFn: () => listEligibleParticipants(eventId, templateId!, { search }), enabled: ready && !!eventId && !!templateId }); }
export function useAwardBadge(eventId: string) { const client = useQueryClient(); return useMutation({ mutationFn: ({ badgeId, registrationId, participantId }: { badgeId: string; registrationId: string; participantId?: string | null }) => awardBadge(eventId, badgeId, registrationId, participantId), onSuccess: () => client.invalidateQueries({ queryKey: ["certificates", eventId] }) }); }
export function useBadgeAwards(eventId: string) { const ready = useSessionStore((s) => s.hydrated && !!s.user); return useQuery({ queryKey: ["certificates", eventId, "badge-awards"], queryFn: () => listBadgeAwards(eventId), enabled: ready && !!eventId }); }
export function useRevokeBadge(eventId: string) { const client = useQueryClient(); return useMutation({ mutationFn: (awardId: string) => revokeBadge(awardId), onSuccess: () => client.invalidateQueries({ queryKey: ["certificates", eventId] }) }); }
export function useBadgeDefinitions(eventId: string) { const ready = useSessionStore((s) => s.hydrated && !!s.user); return useQuery({ queryKey: ["certificates", eventId, "badge-definitions"], queryFn: () => listBadgeDefinitions(eventId), enabled: ready && !!eventId }); }
export function useEligibleBadgeParticipants(eventId: string, badgeId?: string, search?: string) { const ready = useSessionStore((s) => s.hydrated && !!s.user); return useQuery({ queryKey: ["certificates", eventId, "badge-eligible", badgeId, search], queryFn: () => listEligibleBadgeParticipants(eventId, badgeId!, search), enabled: ready && !!eventId && !!badgeId }); }
