import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { createCompetition, createCompetitionMatch, createCompetitionStage, getStandings, listCompetitionMatches, listCompetitions, listCompetitionStages, recordCompetitionResult } from "@/api/competitions";
import { useSessionStore } from "@/state/sessionStore";

export function useEventCompetitions(eventId: string) { const ready = useSessionStore((s) => s.hydrated && !!s.user); return useQuery({ queryKey: ["competitions", eventId], queryFn: () => listCompetitions(eventId), enabled: ready && !!eventId }); }
export function useCompetitionDetails(id: string) { const ready = useSessionStore((s) => s.hydrated && !!s.user); return { stages: useQuery({ queryKey: ["competition", id, "stages"], queryFn: () => listCompetitionStages(id), enabled: ready && !!id }), matches: useQuery({ queryKey: ["competition", id, "matches"], queryFn: () => listCompetitionMatches(id), enabled: ready && !!id }), standings: useQuery({ queryKey: ["competition", id, "standings"], queryFn: () => getStandings(id), enabled: ready && !!id }) }; }
export function useCreateCompetition(eventId: string) { const client = useQueryClient(); return useMutation({ mutationFn: (payload: { name: string; competition_type: string; participation_mode: string }) => createCompetition(eventId, payload), onSuccess: () => client.invalidateQueries({ queryKey: ["competitions", eventId] }) }); }
export function useCreateCompetitionStage(eventId: string, competitionId: string) { const client = useQueryClient(); return useMutation({ mutationFn: (payload: { name: string; stage_type: string; order_index: number }) => createCompetitionStage(eventId, { ...payload, competition_id: competitionId }), onSuccess: () => client.invalidateQueries({ queryKey: ["competition", competitionId, "stages"] }) }); }
export function useCreateCompetitionMatch(competitionId: string) { const client = useQueryClient(); return useMutation({ mutationFn: (payload: { stage_id: string; round_number: number; match_number: number; entry_a_id?: string; entry_b_id?: string; scheduled_start: string; scheduled_end: string; title?: string }) => createCompetitionMatch(competitionId, payload), onSuccess: () => client.invalidateQueries({ queryKey: ["competition", competitionId, "matches"] }) }); }
export function useRecordCompetitionResult(competitionId: string) { const client = useQueryClient(); return useMutation({ mutationFn: ({ matchId, payload }: { matchId: string; payload: { score_a?: number; score_b?: number; result_status: string; winner_entry_id?: string } }) => recordCompetitionResult(matchId, payload), onSuccess: () => { client.invalidateQueries({ queryKey: ["competition", competitionId, "matches"] }); client.invalidateQueries({ queryKey: ["competition", competitionId, "standings"] }); } }); }
