import { apiClient } from "@/api/client";
import type { BadgeDefinition, CertificatePage, CertificateTemplate, EligibleParticipantPage } from "@/types/certificates";
export async function listCertificateTemplates(eventId: string) { const { data } = await apiClient.get<CertificateTemplate[]>(`/certificates/events/${eventId}/templates`); return data; }
export async function upsertCertificateTemplate(eventId: string, payload: Partial<CertificateTemplate>) { const { data } = await apiClient.put<CertificateTemplate>(`/certificates/events/${eventId}/templates`, payload); return data; }
export async function upsertBadgeDefinition(eventId: string, payload: Partial<BadgeDefinition>) { const { data } = await apiClient.put<BadgeDefinition>(`/badges/events/${eventId}`, payload); return data; }
export async function listEventCertificates(eventId: string, filters: { status?: string; page?: number } = {}) { const { data } = await apiClient.get<CertificatePage>(`/certificates/events/${eventId}`, { params: { status: filters.status || undefined, page: filters.page ?? 1, page_size: 25 } }); return data; }
export async function issueCertificate(eventId: string, templateId: string, registrationId: string, participantId?: string | null) { const { data } = await apiClient.post(`/certificates/events/${eventId}/templates/${templateId}/issue`, null, { params: { registration_id: registrationId, participant_id: participantId || undefined } }); return data; }
export async function revokeCertificate(certificateId: string) { const { data } = await apiClient.post(`/certificates/${certificateId}/revoke`); return data; }
export async function listEligibleParticipants(eventId: string, templateId: string, filters: { search?: string; page?: number } = {}) { const { data } = await apiClient.get<EligibleParticipantPage>(`/certificates/events/${eventId}/templates/${templateId}/eligible`, { params: { search: filters.search || undefined, page: filters.page ?? 1, page_size: 25 } }); return data; }
export async function listBadgeAwards(eventId: string, status?: string) { const { data } = await apiClient.get(`/badges/events/${eventId}/awards`, { params: { status: status || undefined, page: 1, page_size: 25 } }); return data; }
export async function awardBadge(eventId: string, badgeId: string, registrationId: string, participantId?: string | null) { const { data } = await apiClient.post(`/badges/events/${eventId}/${badgeId}/award`, null, { params: { registration_id: registrationId, participant_id: participantId || undefined } }); return data; }
export async function revokeBadge(awardId: string) { const { data } = await apiClient.post(`/badges/awards/${awardId}/revoke`); return data; }
export async function listBadgeDefinitions(eventId: string) { const { data } = await apiClient.get<BadgeDefinition[]>(`/badges/events/${eventId}`); return data; }
export async function listEligibleBadgeParticipants(eventId: string, badgeId: string, search?: string) { const { data } = await apiClient.get<import("@/types/certificates").EligibleParticipantPage>(`/badges/events/${eventId}/${badgeId}/eligible`, { params: { search: search || undefined, page: 1, page_size: 25 } }); return data; }
